version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.9
    pre_build:
        commands:
            - aws codeartifact login --tool pip --repository python-private --domain fourzeroone --domain-owner 495963541969 --region eu-central-1
            - python3 -m venv venv
            - source venv/bin/activate
            - python3 -m pip install --upgrade pip
            - pip3 install twine build --upgrade
            - aws codeartifact login --tool twine --repository python-private --domain fourzeroone --domain-owner 495963541969 --region eu-central-1
    build:
        commands:
            - python3 -m build
    post_build:
        commands:
            - twine upload --repository codeartifact dist/*
